# Generated by Django 4.1.7 on 2023-03-16 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_subject_category_subject_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subcategory',
        ),
    ]
